/*******************************************************************************
* File Name: cycfg_capsense_tuner_regmap.h
*
* Description:
* CAPSENSE Tuner register map configuration.
* This file should not be modified. It was automatically generated by
* CAPSENSE Configurator 5.0.0.2684
*
********************************************************************************
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company) 
* or an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_CAPSENSE_TUNER_REGMAP_H)
#define CYCFG_CAPSENSE_TUNER_REGMAP_H

#include "cy_capsense_common.h"

#if !defined(CY_CAPSENSE_MW_VERSION)
    #define CY_CAPSENSE_TUNER_MW_VERSION (200)
#else
    #define CY_CAPSENSE_TUNER_MW_VERSION (CY_CAPSENSE_MW_VERSION)
#endif

/* RAM Data structure register definitions */
#if (CY_CAPSENSE_TUNER_MW_VERSION < 300)
#define CY_CAPSENSE_TUNER_CONFIG_ID_OFFSET                                             (0u)
#define CY_CAPSENSE_TUNER_CONFIG_ID_SIZE                                               (2u)

#define CY_CAPSENSE_TUNER_TUNER_CMD_OFFSET                                             (2u)
#define CY_CAPSENSE_TUNER_TUNER_CMD_SIZE                                               (2u)

#define CY_CAPSENSE_TUNER_SCAN_COUNTER_OFFSET                                          (4u)
#define CY_CAPSENSE_TUNER_SCAN_COUNTER_SIZE                                            (2u)

#define CY_CAPSENSE_TUNER_TUNER_ST_OFFSET                                              (6u)
#define CY_CAPSENSE_TUNER_TUNER_ST_SIZE                                                (1u)

#define CY_CAPSENSE_TUNER_INITDONE_OFFSET                                              (7u)
#define CY_CAPSENSE_TUNER_INITDONE_SIZE                                                (1u)

#define CY_CAPSENSE_TUNER_PTRSSCALLBACK_OFFSET                                         (8u)
#define CY_CAPSENSE_TUNER_PTRSSCALLBACK_SIZE                                           (4u)

#define CY_CAPSENSE_TUNER_PTREOSCALLBACK_OFFSET                                        (12u)
#define CY_CAPSENSE_TUNER_PTREOSCALLBACK_SIZE                                          (4u)

#define CY_CAPSENSE_TUNER_PTRTUNERSENDCALLBACK_OFFSET                                  (16u)
#define CY_CAPSENSE_TUNER_PTRTUNERSENDCALLBACK_SIZE                                    (4u)

#define CY_CAPSENSE_TUNER_PTRTUNERRECEIVECALLBACK_OFFSET                               (20u)
#define CY_CAPSENSE_TUNER_PTRTUNERRECEIVECALLBACK_SIZE                                 (4u)

#define CY_CAPSENSE_TUNER_STATUS_OFFSET                                                (24u)
#define CY_CAPSENSE_TUNER_STATUS_SIZE                                                  (4u)

#define CY_CAPSENSE_TUNER_TIMESTAMPINTERVAL_OFFSET                                     (28u)
#define CY_CAPSENSE_TUNER_TIMESTAMPINTERVAL_SIZE                                       (4u)

#define CY_CAPSENSE_TUNER_TIMESTAMP_OFFSET                                             (32u)
#define CY_CAPSENSE_TUNER_TIMESTAMP_SIZE                                               (4u)

#define CY_CAPSENSE_TUNER_CSD_MOD_CLK_DIVIDER_OFFSET                                   (36u)
#define CY_CAPSENSE_TUNER_CSD_MOD_CLK_DIVIDER_SIZE                                     (1u)

#define CY_CAPSENSE_TUNER_CSX_MOD_CLK_DIVIDER_OFFSET                                   (37u)
#define CY_CAPSENSE_TUNER_CSX_MOD_CLK_DIVIDER_SIZE                                     (1u)

#define CY_CAPSENSE_TUNER_TUNER_CNT_OFFSET                                             (38u)
#define CY_CAPSENSE_TUNER_TUNER_CNT_SIZE                                               (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_FINGER_CP_OFFSET                                  (40u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_FINGER_CP_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SIGPFC_OFFSET                                     (42u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SIGPFC_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_RESOLUTION_OFFSET                                 (44u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_RESOLUTION_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_MAX_RAW_COUNT_OFFSET                              (46u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_MAX_RAW_COUNT_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_FINGER_TH_OFFSET                                  (48u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_FINGER_TH_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_PROX_TOUCH_TH_OFFSET                              (50u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_PROX_TOUCH_TH_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_LOW_BSLN_RST_OFFSET                               (52u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_LOW_BSLN_RST_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS_CLK_OFFSET                                    (54u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS_CLK_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_SNS_CLK_OFFSET                                (56u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_SNS_CLK_SIZE                                  (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_GESTURE_DETECTED_OFFSET                           (58u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_GESTURE_DETECTED_SIZE                             (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_GESTURE_DIRECTION_OFFSET                          (60u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_GESTURE_DIRECTION_SIZE                            (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_XDELTA_OFFSET                                     (62u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_XDELTA_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_YDELTA_OFFSET                                     (64u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_YDELTA_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_NOISE_TH_OFFSET                                   (66u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_NOISE_TH_SIZE                                     (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_NNOISE_TH_OFFSET                                  (67u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_NNOISE_TH_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_HYSTERESIS_OFFSET                                 (68u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_HYSTERESIS_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ON_DEBOUNCE_OFFSET                                (69u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ON_DEBOUNCE_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS_CLK_SOURCE_OFFSET                             (70u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS_CLK_SOURCE_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD0_OFFSET                                  (71u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD0_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD1_OFFSET                                  (72u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD1_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD2_OFFSET                                  (73u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD2_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_GAIN_INDEX_OFFSET                            (74u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_GAIN_INDEX_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD0_OFFSET                              (75u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD1_OFFSET                              (76u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD1_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD2_OFFSET                              (77u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD2_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_PROX_IIR_BL_N_OFFSET                              (78u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_PROX_IIR_BL_N_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_STATUS_OFFSET                                     (79u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_STATUS_SIZE                                       (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_PTRPOSITION_OFFSET                                (80u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_PTRPOSITION_SIZE                                  (4u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_NUM_POSITIONS_OFFSET                              (84u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_NUM_POSITIONS_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_FINGER_CP_OFFSET                                  (88u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_FINGER_CP_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SIGPFC_OFFSET                                     (90u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SIGPFC_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_RESOLUTION_OFFSET                                 (92u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_RESOLUTION_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_MAX_RAW_COUNT_OFFSET                              (94u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_MAX_RAW_COUNT_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_FINGER_TH_OFFSET                                  (96u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_FINGER_TH_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_PROX_TOUCH_TH_OFFSET                              (98u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_PROX_TOUCH_TH_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_LOW_BSLN_RST_OFFSET                               (100u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_LOW_BSLN_RST_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS_CLK_OFFSET                                    (102u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS_CLK_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_SNS_CLK_OFFSET                                (104u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_SNS_CLK_SIZE                                  (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_GESTURE_DETECTED_OFFSET                           (106u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_GESTURE_DETECTED_SIZE                             (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_GESTURE_DIRECTION_OFFSET                          (108u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_GESTURE_DIRECTION_SIZE                            (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_XDELTA_OFFSET                                     (110u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_XDELTA_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_YDELTA_OFFSET                                     (112u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_YDELTA_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_NOISE_TH_OFFSET                                   (114u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_NOISE_TH_SIZE                                     (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_NNOISE_TH_OFFSET                                  (115u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_NNOISE_TH_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_HYSTERESIS_OFFSET                                 (116u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_HYSTERESIS_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ON_DEBOUNCE_OFFSET                                (117u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ON_DEBOUNCE_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS_CLK_SOURCE_OFFSET                             (118u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS_CLK_SOURCE_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD0_OFFSET                                  (119u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD0_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD1_OFFSET                                  (120u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD1_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD2_OFFSET                                  (121u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD2_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_GAIN_INDEX_OFFSET                            (122u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_GAIN_INDEX_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD0_OFFSET                              (123u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD1_OFFSET                              (124u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD1_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD2_OFFSET                              (125u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD2_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_PROX_IIR_BL_N_OFFSET                              (126u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_PROX_IIR_BL_N_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_STATUS_OFFSET                                     (127u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_STATUS_SIZE                                       (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_PTRPOSITION_OFFSET                                (128u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_PTRPOSITION_SIZE                                  (4u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_NUM_POSITIONS_OFFSET                              (132u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_NUM_POSITIONS_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_RAW0_OFFSET                                  (136u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_BSLN0_OFFSET                                 (138u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_DIFF0_OFFSET                                 (140u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_STATUS0_OFFSET                               (142u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_NEG_BSLN_RST_CNT0_OFFSET                     (143u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_IDAC0_OFFSET                                 (144u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_IDAC0_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_BSLN_EXT0_OFFSET                             (145u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_BSLN_EXT0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_RAW0_OFFSET                                  (146u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_BSLN0_OFFSET                                 (148u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_DIFF0_OFFSET                                 (150u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_STATUS0_OFFSET                               (152u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_NEG_BSLN_RST_CNT0_OFFSET                     (153u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_IDAC0_OFFSET                                 (154u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_IDAC0_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_BSLN_EXT0_OFFSET                             (155u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_BSLN_EXT0_SIZE                               (1u)

#else /* CY_CAPSENSE_TUNER_MW_VERSION >= 300 */
#define CY_CAPSENSE_TUNER_CONFIG_ID_OFFSET                                             (0u)
#define CY_CAPSENSE_TUNER_CONFIG_ID_SIZE                                               (2u)

#define CY_CAPSENSE_TUNER_TUNER_CMD_OFFSET                                             (2u)
#define CY_CAPSENSE_TUNER_TUNER_CMD_SIZE                                               (2u)

#define CY_CAPSENSE_TUNER_SCAN_COUNTER_OFFSET                                          (4u)
#define CY_CAPSENSE_TUNER_SCAN_COUNTER_SIZE                                            (2u)

#define CY_CAPSENSE_TUNER_TUNER_ST_OFFSET                                              (6u)
#define CY_CAPSENSE_TUNER_TUNER_ST_SIZE                                                (1u)

#define CY_CAPSENSE_TUNER_INITDONE_OFFSET                                              (7u)
#define CY_CAPSENSE_TUNER_INITDONE_SIZE                                                (1u)

#define CY_CAPSENSE_TUNER_STATUS_OFFSET                                                (8u)
#define CY_CAPSENSE_TUNER_STATUS_SIZE                                                  (4u)

#define CY_CAPSENSE_TUNER_TIMESTAMPINTERVAL_OFFSET                                     (12u)
#define CY_CAPSENSE_TUNER_TIMESTAMPINTERVAL_SIZE                                       (4u)

#define CY_CAPSENSE_TUNER_TIMESTAMP_OFFSET                                             (16u)
#define CY_CAPSENSE_TUNER_TIMESTAMP_SIZE                                               (4u)

#define CY_CAPSENSE_TUNER_CSD_MOD_CLK_DIVIDER_OFFSET                                   (20u)
#define CY_CAPSENSE_TUNER_CSD_MOD_CLK_DIVIDER_SIZE                                     (1u)

#define CY_CAPSENSE_TUNER_CSX_MOD_CLK_DIVIDER_OFFSET                                   (21u)
#define CY_CAPSENSE_TUNER_CSX_MOD_CLK_DIVIDER_SIZE                                     (1u)

#define CY_CAPSENSE_TUNER_TUNER_CNT_OFFSET                                             (22u)
#define CY_CAPSENSE_TUNER_TUNER_CNT_SIZE                                               (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_FINGER_CP_OFFSET                                  (24u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_FINGER_CP_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SIGPFC_OFFSET                                     (26u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SIGPFC_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_RESOLUTION_OFFSET                                 (28u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_RESOLUTION_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_MAX_RAW_COUNT_OFFSET                              (30u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_MAX_RAW_COUNT_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_MAX_RAW_COUNT_OFFSET                          (32u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_MAX_RAW_COUNT_SIZE                            (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_FINGER_TH_OFFSET                                  (34u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_FINGER_TH_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_PROX_TOUCH_TH_OFFSET                              (36u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_PROX_TOUCH_TH_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_LOW_BSLN_RST_OFFSET                               (38u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_LOW_BSLN_RST_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS_CLK_OFFSET                                    (40u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS_CLK_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_SNS_CLK_OFFSET                                (42u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_SNS_CLK_SIZE                                  (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_GESTURE_DETECTED_OFFSET                           (44u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_GESTURE_DETECTED_SIZE                             (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_GESTURE_DIRECTION_OFFSET                          (46u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_GESTURE_DIRECTION_SIZE                            (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_XDELTA_OFFSET                                     (48u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_XDELTA_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_YDELTA_OFFSET                                     (50u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_YDELTA_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_NOISE_TH_OFFSET                                   (52u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_NOISE_TH_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_NNOISE_TH_OFFSET                                  (54u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_NNOISE_TH_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_HYSTERESIS_OFFSET                                 (56u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_HYSTERESIS_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ON_DEBOUNCE_OFFSET                                (58u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ON_DEBOUNCE_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS_CLK_SOURCE_OFFSET                             (59u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS_CLK_SOURCE_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD0_OFFSET                                  (60u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD0_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD1_OFFSET                                  (61u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD1_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD2_OFFSET                                  (62u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_MOD2_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_GAIN_INDEX_OFFSET                            (63u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_IDAC_GAIN_INDEX_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD0_OFFSET                              (64u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD1_OFFSET                              (65u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD1_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD2_OFFSET                              (66u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_ROW_IDAC_MOD2_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_PROX_IIR_BL_N_OFFSET                              (67u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_PROX_IIR_BL_N_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_STATUS_OFFSET                                     (68u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_STATUS_SIZE                                       (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_PTRPOSITION_OFFSET                                (72u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_PTRPOSITION_SIZE                                  (4u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_NUM_POSITIONS_OFFSET                              (76u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_NUM_POSITIONS_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_FINGER_CP_OFFSET                                  (80u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_FINGER_CP_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SIGPFC_OFFSET                                     (82u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SIGPFC_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_RESOLUTION_OFFSET                                 (84u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_RESOLUTION_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_MAX_RAW_COUNT_OFFSET                              (86u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_MAX_RAW_COUNT_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_MAX_RAW_COUNT_OFFSET                          (88u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_MAX_RAW_COUNT_SIZE                            (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_FINGER_TH_OFFSET                                  (90u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_FINGER_TH_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_PROX_TOUCH_TH_OFFSET                              (92u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_PROX_TOUCH_TH_SIZE                                (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_LOW_BSLN_RST_OFFSET                               (94u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_LOW_BSLN_RST_SIZE                                 (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS_CLK_OFFSET                                    (96u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS_CLK_SIZE                                      (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_SNS_CLK_OFFSET                                (98u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_SNS_CLK_SIZE                                  (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_GESTURE_DETECTED_OFFSET                           (100u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_GESTURE_DETECTED_SIZE                             (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_GESTURE_DIRECTION_OFFSET                          (102u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_GESTURE_DIRECTION_SIZE                            (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_XDELTA_OFFSET                                     (104u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_XDELTA_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_YDELTA_OFFSET                                     (106u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_YDELTA_SIZE                                       (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_NOISE_TH_OFFSET                                   (108u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_NOISE_TH_SIZE                                     (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_NNOISE_TH_OFFSET                                  (110u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_NNOISE_TH_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_HYSTERESIS_OFFSET                                 (112u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_HYSTERESIS_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ON_DEBOUNCE_OFFSET                                (114u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ON_DEBOUNCE_SIZE                                  (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS_CLK_SOURCE_OFFSET                             (115u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS_CLK_SOURCE_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD0_OFFSET                                  (116u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD0_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD1_OFFSET                                  (117u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD1_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD2_OFFSET                                  (118u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_MOD2_SIZE                                    (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_GAIN_INDEX_OFFSET                            (119u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_IDAC_GAIN_INDEX_SIZE                              (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD0_OFFSET                              (120u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD0_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD1_OFFSET                              (121u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD1_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD2_OFFSET                              (122u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_ROW_IDAC_MOD2_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_PROX_IIR_BL_N_OFFSET                              (123u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_PROX_IIR_BL_N_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_STATUS_OFFSET                                     (124u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_STATUS_SIZE                                       (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_PTRPOSITION_OFFSET                                (128u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_PTRPOSITION_SIZE                                  (4u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_NUM_POSITIONS_OFFSET                              (132u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_NUM_POSITIONS_SIZE                                (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_RAW0_OFFSET                                  (136u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_BSLN0_OFFSET                                 (138u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_DIFF0_OFFSET                                 (140u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_STATUS0_OFFSET                               (142u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_NEG_BSLN_RST_CNT0_OFFSET                     (143u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_IDAC0_OFFSET                                 (144u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_IDAC0_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_BSLN_EXT0_OFFSET                             (145u)
#define CY_CAPSENSE_TUNER_PROXIMITY0_SNS0_BSLN_EXT0_SIZE                               (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_RAW0_OFFSET                                  (146u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_RAW0_SIZE                                    (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_BSLN0_OFFSET                                 (148u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_BSLN0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_DIFF0_OFFSET                                 (150u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_DIFF0_SIZE                                   (2u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_STATUS0_OFFSET                               (152u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_STATUS0_SIZE                                 (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_NEG_BSLN_RST_CNT0_OFFSET                     (153u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_NEG_BSLN_RST_CNT0_SIZE                       (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_IDAC0_OFFSET                                 (154u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_IDAC0_SIZE                                   (1u)

#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_BSLN_EXT0_OFFSET                             (155u)
#define CY_CAPSENSE_TUNER_PROXIMITYW_SNS0_BSLN_EXT0_SIZE                               (1u)

#endif


#endif /* CYCFG_CAPSENSE_TUNER_REGMAP_H */

/* [] END OF FILE */
