#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries
SEARCH_TARGET_CYSBSYSKIT-DEV-01=./libs/TARGET_CYSBSYSKIT-DEV-01



# The search paths for the included middleware
SEARCH_capsense=../mtb_shared/capsense/latest-v3.X
SEARCH_freertos=../mtb_shared/freertos/release-v10.4.305
SEARCH_retarget-io=../mtb_shared/retarget-io/release-v1.4.0
SEARCH_xensiv-radar-sensing=../mtb_shared/xensiv-radar-sensing/release-v1.1.0
SEARCH_abstraction-rtos=../mtb_shared/abstraction-rtos/release-v1.7.1
SEARCH_clib-support=../mtb_shared/clib-support/release-v1.3.0
SEARCH_core-lib=../mtb_shared/core-lib/release-v1.3.1
SEARCH_core-make=../mtb_shared/core-make/release-v1.9.1
SEARCH_mtb-hal-cat1=../mtb_shared/mtb-hal-cat1/release-v2.3.0
SEARCH_mtb-pdl-cat1=../mtb_shared/mtb-pdl-cat1/release-v2.4.1
SEARCH_psoc6cm0p=../mtb_shared/psoc6cm0p/release-v2.3.0
SEARCH_recipe-make-cat1a=../mtb_shared/recipe-make-cat1a/release-v1.9.0

# Search libraries added to build
SEARCH+=$(SEARCH_capsense)
SEARCH+=$(SEARCH_freertos)
SEARCH+=$(SEARCH_retarget-io)
SEARCH+=$(SEARCH_xensiv-radar-sensing)
SEARCH+=$(SEARCH_abstraction-rtos)
SEARCH+=$(SEARCH_clib-support)
SEARCH+=$(SEARCH_core-lib)
SEARCH+=$(SEARCH_core-make)
SEARCH+=$(SEARCH_mtb-hal-cat1)
SEARCH+=$(SEARCH_mtb-pdl-cat1)
SEARCH+=$(SEARCH_psoc6cm0p)
SEARCH+=$(SEARCH_recipe-make-cat1a)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_CAPSENSE
COMPONENTS += MW_FREERTOS
COMPONENTS += MW_RETARGET_IO
COMPONENTS += MW_TARGET_CYSBSYSKIT_DEV_01
COMPONENTS += MW_XENSIV_RADAR_SENSING
COMPONENTS += MW_ABSTRACTION_RTOS
COMPONENTS += MW_CLIB_SUPPORT
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_MTB_HAL_CAT1
COMPONENTS += MW_MTB_PDL_CAT1
COMPONENTS += MW_PSOC6CM0P
COMPONENTS += MW_RECIPE_MAKE_CAT1A
